class_name Enums

enum Upgrade { 
	HEAL_MINOR, HEAL_MID, HEAL_MAJOR, 
	CLAW_DMG, CLAW_SPEED, CLAW_SIZE,
	TAILWHIP, TAILWHIP_DMG, TAILWHIP_SPEED, TAILWHIP_SIZE,
	FURBALL, FURBALL_DMG, FURBALL_SPEED, FURBALL_PROJECTILE
 }
